db.createCollection("Measurements")
db.Measurements.createIndex({ First: 1 })
db.Measurements.createIndex({ Last: 1 })
db.Measurements.createIndex({ SensorId: "hashed" }, { expireAfterSeconds: 10368000 })
db.Measurements.createIndex({ Timestamp: 1 })
db.Measurements.createIndex({ Count: 1 })
db.Measurements.createIndex({ "Measurements.Timestamp": 1 })
